In [18]:
import pandas as pd

In [24]:
energy_use2019 = pd.read_csv("energy_distribution_data_CY2019.csv")
energy_use2019

,BUILDING_NUMBER,BUILDING_NAME_LONG,BUILDING_GROUP_LEVEL1,CLUSTER_NUM,BUILDING_TYPE,BUILDING_USE,SITE,CAMPUS_SECTOR,YEAR_CONST_BEGAN,YEAR_OCCUPIED,...,NUMBER_OF_UNITS,UNIT_OF_MEASURE,MMBTU,kBTU,GHG,PI_CONNECTION,METER_STATUS,START_DATE,END_DATE,START_DATE_USE
0,1,Henry L Pierce Engineering Laboratory,Non-CUP,Lab & Mixed Use,ACADEMIC,AER,MIT,MAIN GROUP,1913.0,1917.0,...,31355.0,THR,376.260000,376260.000,12.400213,Y,Chilled Water Only,2019-06-01,2019-06-30,2019-05-01
1,1,Henry L Pierce Engineering Laboratory,Non-CUP,Lab & Mixed Use,ACADEMIC,AER,MIT,MAIN GROUP,1913.0,1917.0,...,30357.0,THR,364.284000,364284.000,12.005526,Y,Chilled Water Only,2019-05-01,2019-05-31,2019-04-01
2,1,Henry L Pierce Engineering Laboratory,Non-CUP,Lab & Mixed Use,ACADEMIC,AER,MIT,MAIN GROUP,1913.0,1917.0,...,28406.0,THR,340.872000,340872.000,11.233948,Y,Chilled Water Only,2019-07-01,2019-07-31,2019-06-01
3,1,Henry L Pierce Engineering Laboratory,Non-CUP,Lab & Mixed Use,ACADEMIC,AER,MIT,MAIN GROUP,1913.0,1917.0,...,335526.0,KWH,1145.150238,1145150.238,100.773221,Y,Chilled Water Only,2019-10-01,2019-10-31,2019-09-01
4,1,Henry L Pierce Engineering Laboratory,Non-CUP,Lab & Mixed Use,ACADEMIC,AER,MIT,MAIN GROUP,1913.0,1917.0,...,183320.0,KWH,625.671160,625671.160,55.059062,Y,Chilled Water Only,2019-11-01,2019-11-30,2019-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4210,WW15,Building WW15,Non-CUP,Support Dominant,SERVICE,AER,MIT,WESTWEST,1969.0,NaN,...,17600.0,KWH,60.051200,60051.200,5.966400,N,No Individual Metering,2019-02-01,2019-02-28,2019-01-01
4211,WW15,Building WW15,Non-CUP,Support Dominant,SERVICE,AER,MIT,WESTWEST,1969.0,NaN,...,16400.0,KWH,55.956800,55956.800,5.559600,N,No Individual Metering,2019-04-01,2019-04-30,2019-03-01
4212,WW15,Building WW15,Non-CUP,Support Dominant,SERVICE,AER,MIT,WESTWEST,1969.0,NaN,...,18360.0,KWH,62.644320,62644.320,6.224040,N,No Individual Metering,2019-03-01,2019-03-31,2019-02-01
4213,WW15,Building WW15,Non-CUP,Support Dominant,SERVICE,AER,MIT,WESTWEST,1969.0,NaN,...,15240.0,KWH,51.998880,51998.880,5.166360,N,No Individual Metering,2019-06-01,2019-06-30,2019-05-01
4214,WW15,Building WW15,Non-CUP,Support Dominant,SERVICE,AER,MIT,WESTWEST,1969.0,NaN,...,16800.0,KWH,57.321600,57321.600,5.695200,N,No Individual Metering,2019-05-01,2019-05-31,2019-04-01

In [25]:
energy_use2019.columns

Index(['BUILDING_NUMBER', 'BUILDING_NAME_LONG', 'BUILDING_GROUP_LEVEL1',
       'CLUSTER_NUM', 'BUILDING_TYPE', 'BUILDING_USE', 'SITE', 'CAMPUS_SECTOR',
       'YEAR_CONST_BEGAN', 'YEAR_OCCUPIED', 'LATITUDE_WGS', 'LONGITUDE_WGS',
       'OWNERSHIP_TYPE', 'BUILDING_HEIGHT', 'NUM_OF_ROOMS', 'EXT_GROSS_AREA',
       'ASSIGNABLE_AREA', 'NON_ASSIGNABLE_AREA', 'BLDG_SRV', 'CIRCULAT',
       'CLASSRMS', 'GENERAL', 'HEALTH', 'LABS', 'MECHANIC', 'OFFICES',
       'RESIDENT', 'SPECIAL', 'STUDY', 'SUPPORT', 'UNCLASS', 'USEABLE_AREA',
       'STRUCT_AREA', 'LEVEL3_CATEGORY', 'LEVEL2_CATEGORY', 'NUMBER_OF_UNITS',
       'UNIT_OF_MEASURE', 'MMBTU', 'kBTU', 'GHG', 'PI_CONNECTION',
       'METER_STATUS', 'START_DATE', 'END_DATE', 'START_DATE_USE'],
      dtype='object')

In [28]:
energy_use2019.groupby("LEVEL3_CATEGORY")

,YEAR_CONST_BEGAN,YEAR_OCCUPIED,LATITUDE_WGS,LONGITUDE_WGS,BUILDING_HEIGHT,NUM_OF_ROOMS,EXT_GROSS_AREA,ASSIGNABLE_AREA,NON_ASSIGNABLE_AREA,BLDG_SRV,...,SPECIAL,STUDY,SUPPORT,UNCLASS,USEABLE_AREA,STRUCT_AREA,NUMBER_OF_UNITS,MMBTU,kBTU,GHG
LEVEL3_CATEGORY,,,,,,,,,,,,,,,,,,,,,
Chilled Water,1951.010574,1961.183976,42.360228,-71.091387,79.079586,393.419481,126301.803335,71685.970273,41490.635273,1982.565156,...,2949.354597,2168.542416,2264.213831,115.173675,113332.060403,12969.742932,-99.401299,-1.192816,-1.192816e+03,-0.039311
Electricity,1948.503597,1963.539792,42.362157,-71.097292,66.946308,306.306924,103637.312217,62870.232157,29606.685413,1690.054503,...,2917.255054,1450.460879,6837.823295,218.341691,92569.434973,10886.584403,101957.530280,347.886160,3.478862e+05,34.601516
Fuel Oil #2,1936.000000,1937.000000,42.358517,-71.087730,21.300000,139.909091,99460.800909,43250.930000,42089.371818,275.589091,...,1540.465455,0.000000,2883.414545,15.272727,87153.941818,12306.859091,3698.530478,522.384424,5.223844e+05,38.233372
Gas,1949.723338,1967.968703,42.359592,-71.094451,65.989702,344.696576,112412.583658,66939.601854,32973.382290,1806.089067,...,3244.751688,1230.627839,2696.959563,84.462007,100048.418300,12364.165358,29041.623070,2962.003365,2.962003e+06,157.528225
Steam,1949.787485,1959.503505,42.359761,-71.092008,80.621262,378.265060,120659.867307,69224.988384,38173.861436,2191.313679,...,3833.826951,1807.766870,1986.851880,91.226829,107649.956504,12942.984307,-1.053946,-1.159341,-1.159341e+03,-0.069560